/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_knight_ndktest_Hello */

#ifndef _Included_com_knight_ndktest_Hello
#define _Included_com_knight_ndktest_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_knight_ndktest_Hello
 * Method:    test
 * Signature: ()Lcom/knight/ndktest/Student;
 */
JNIEXPORT jobject JNICALL Java_com_knight_ndktest_Hello_test
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
