/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string>
/* Header for class com_knight_ndktest_Hello */

#ifndef _Included_com_knight_ndktest_Hello
#define _Included_com_knight_ndktest_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_knight_ndktest_Hello
 * Method:    test
 * Signature: ()Lcom/knight/ndktest/Student;
 */
JNIEXPORT jobject JNICALL Java_com_knight_ndktest_Hello_test
        (JNIEnv *, jclass);

/*
 * Class:     com_knight_ndktest_MainActivity
 * Method:    stringFromJNI
 * Signature: ()String;
 */
JNIEXPORT jstring JNICALL Java_com_knight_ndktest_MainActivity_stringFromJNI
        (JNIEnv *, jclass);
#ifdef __cplusplus
}
#endif
#endif
